services:
  - type: web
    name: vclock
    env: node
    rootDir: .
    buildCommand: cd frontend && npm ci && npm run build && cd ../backend && npm ci
    startCommand: cd backend && npm start
    autoDeploy: true
